development:
  adapter: postgresql
  database: parcrawl_development
  user: viget
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: parcrawl_test
  user: viget
  host: localhost
  pool: 5
  timeout: 5000